sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.22.0

services:
  - docker

script:
  - docker network create ds_proxy_default
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml build
