version: '3'

services:
  nginx:
    image: nginx:1.11-alpine
    environment:
      - VIRTUAL_HOST
    volumes:
      - '${DIRECTORY}/docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - '${DIRECTORY}/web:/srv/discovery/web'

networks:
  default:
    external:
      name: '${NETWORK}'
