version: '3'

services:
  client_1: &hosts
    extra_hosts:
      - 'api.assets.stag.ds:${PROXY_HOST}'
      - 'api.authentication.stag.ds:${PROXY_HOST}'
      - 'api.camunda.stag.ds:${PROXY_HOST}'
      - 'api.cases.stag.ds:${PROXY_HOST}'
      - 'api.cms.stag.ds:${PROXY_HOST}'
      - 'api.discovery.stag.ds:${PROXY_HOST}'
      - 'api.formio.stag.ds:${PROXY_HOST}'
      - 'api.forms.stag.ds:${PROXY_HOST}'
      - 'api.identities.stag.ds:${PROXY_HOST}'
      - 'api.interactions.stag.ds:${PROXY_HOST}'
      - 'api.logs.stag.ds:${PROXY_HOST}'
      - 'api.records.stag.ds:${PROXY_HOST}'
      - 'api.services.stag.ds:${PROXY_HOST}'
      - 'api.tasks.stag.ds:${PROXY_HOST}'
      - 'api.tenants.stag.ds:${PROXY_HOST}'
      - 'api.topics.stag.ds:${PROXY_HOST}'

  client_2: *hosts

  client_3: *hosts

  server_1: *hosts

  server_2: *hosts

  bootstrap: *hosts
