version: '3'

services:
  client: &agent
    image: consul:1.2.2
    environment:
      CONSUL_LOCAL_CONFIG: '${CONFIG}'
      SERVICE_IGNORE: 'true'
    command: 'agent'
    volumes:
      - '${DIRECTORY}/agent/agent.json:/consul/config/agent.json'
      - '${DIRECTORY}/agent/acl.json:/consul/config/acl.json'
      - '${DIRECTORY}/client/agent.json:/consul/config/client.json'
      - client_data:/consul/data

  server:
    <<: *agent
    volumes:
      - '${DIRECTORY}/agent/agent.json:/consul/config/agent.json'
      - '${DIRECTORY}/agent/acl.json:/consul/config/acl.json'
      - '${DIRECTORY}/server/agent.json:/consul/config/server.json'
      - server_data:/consul/data

  bootstrap:
    <<: *agent
    environment:
      CONSUL_LOCAL_CONFIG: '${CONFIG}'
      SERVICE_8300_IGNORE: 'true'
      SERVICE_8301_IGNORE: 'true'
      SERVICE_8302_IGNORE: 'true'
      SERVICE_8600_IGNORE: 'true'
      SERVICE_8500_ID: '${COMPOSE_PROJECT_NAME}_bootstrap_8500'
      SERVICE_8500_NAME: '${COMPOSE_PROJECT_NAME}_bootstrap_8500'
      SERVICE_8500_TAGS: 'proxy.enable=true,proxy.tags=external,proxy.frontend.entryPoints=http,proxy.frontend.rule=Host:${BOOTSTRAP_HOST}'
    volumes:
      - '${DIRECTORY}/agent/agent.json:/consul/config/agent.json'
      - '${DIRECTORY}/agent/acl.json:/consul/config/acl.json'
      - '${DIRECTORY}/bootstrap/agent.json:/consul/config/bootstrap.json'
      - bootstrap_data:/consul/data

  registrator:
    image: gliderlabs/registrator:v7
    depends_on:
      - bootstrap
    environment:
      CONSUL_HTTP_TOKEN: '${DISCOVERY_TOKEN}'
    command: '-internal consul://bootstrap:8500'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  client_data:
    driver: local

  server_data:
    driver: local

  bootstrap_data:
    driver: local

networks:
  default:
    external:
      name: '${NETWORK}'
