version: '3.4'

services:
  client:
    image: digitalstate/discovery-client
    build:
      context: ./client
    environment:
      CONSUL_LOCAL_CONFIG: ${CONFIG}
    command: agent
    volumes:
      - client_data:/consul/data
    networks:
      default:
        aliases:
          - discovery_client

  server:
    image: digitalstate/discovery-server
    build:
      context: ./server
    environment:
      CONSUL_LOCAL_CONFIG: ${CONFIG}
    command: agent
    volumes:
      - server_data:/consul/data
    networks:
      default:
        aliases:
          - discovery_server

  bootstrap:
    image: digitalstate/discovery-bootstrap
    build:
      context: ./bootstrap
    environment:
      CONSUL_LOCAL_CONFIG: ${CONFIG}
    command: agent
    volumes:
      - bootstrap_data:/consul/data
    networks:
      default:
        aliases:
          - discovery_bootstrap

volumes:
  client_data:
    driver: local

  server_data:
    driver: local

  bootstrap_data:
    driver: local
