version: '3'

services:
  client_1:
    extra_hosts: &hosts
      - 'api.assets.dev.ds:${PROXY_HOST}'
      - 'api.authentication.dev.ds:${PROXY_HOST}'
      - 'api.camunda.dev.ds:${PROXY_HOST}'
      - 'api.cases.dev.ds:${PROXY_HOST}'
      - 'api.cms.dev.ds:${PROXY_HOST}'
      - 'api.discovery.dev.ds:${PROXY_HOST}'
      - 'api.formio.dev.ds:${PROXY_HOST}'
      - 'api.forms.dev.ds:${PROXY_HOST}'
      - 'api.identities.dev.ds:${PROXY_HOST}'
      - 'api.interactions.dev.ds:${PROXY_HOST}'
      - 'api.logs.dev.ds:${PROXY_HOST}'
      - 'api.records.dev.ds:${PROXY_HOST}'
      - 'api.services.dev.ds:${PROXY_HOST}'
      - 'api.tasks.dev.ds:${PROXY_HOST}'
      - 'api.tenants.dev.ds:${PROXY_HOST}'
      - 'api.topics.dev.ds:${PROXY_HOST}'

  client_2:
    extra_hosts: *hosts

  client_3:
    extra_hosts: *hosts

  server_1:
    extra_hosts: *hosts

  server_2:
    extra_hosts: *hosts

  bootstrap:
    extra_hosts: *hosts
