version: '3'

services:
  client_1:
    extra_hosts: &hosts
      - 'api.assets.prod.ds:${PROXY_HOST}'
      - 'api.authentication.prod.ds:${PROXY_HOST}'
      - 'api.camunda.prod.ds:${PROXY_HOST}'
      - 'api.cases.prod.ds:${PROXY_HOST}'
      - 'api.cms.prod.ds:${PROXY_HOST}'
      - 'api.discovery.prod.ds:${PROXY_HOST}'
      - 'api.formio.prod.ds:${PROXY_HOST}'
      - 'api.forms.prod.ds:${PROXY_HOST}'
      - 'api.identities.prod.ds:${PROXY_HOST}'
      - 'api.interactions.prod.ds:${PROXY_HOST}'
      - 'api.logs.prod.ds:${PROXY_HOST}'
      - 'api.records.prod.ds:${PROXY_HOST}'
      - 'api.services.prod.ds:${PROXY_HOST}'
      - 'api.tasks.prod.ds:${PROXY_HOST}'
      - 'api.tenants.prod.ds:${PROXY_HOST}'
      - 'api.topics.prod.ds:${PROXY_HOST}'

  client_2:
    extra_hosts: *hosts

  client_3:
    extra_hosts: *hosts

  server_1:
    extra_hosts: *hosts

  server_2:
    extra_hosts: *hosts

  bootstrap:
    extra_hosts: *hosts
